
  <h2><i class="fas fa-utensils"></i> Réservation d'une table</h2>
  <form method="POST" action="index.php?action=booking" id="form_resa">
    <fieldset class="authentification">
      <legend>Informations</legend>
        <label for="dateResa">Date de réservation: </label>
        <input name="dateResa" type="date" value="<?= date("Y-m-d") ?>" min="<?= date("Y-m-d") ?>">
        <label for="booking_hour">à:</label>
        <select name="booking_hour" id="booking_hour">
          <?php for($i=12; $i<14; $i++): ?>
            <option value="<?=$i?>"><?=$i?></option>
          <?php endfor; ?>
           <?php for($i=18; $i<21; $i++): ?>
            <option value="<?=$i?>"><?=$i?></option>
          <?php endfor; ?>
        </select>
        <select name="booking_min" id="booking_min">
          <option value="00">00</option>
          <option value="15">15</option>
          <option value="30">30</option>
          <option value="45">45</option>
        </select>
        <label for="nb_couverts" >Nombre de couverts: </label>
        <input type="number" name="nb_couverts" min="1" max="35" value="2">
    </fieldset>
    <input type="submit" name="reserver" value="Réserver" class="button">
    <a href="../index.php" class="cancel">Annuler</a>
  </form>
